const fs = require('fs');
const path = require('path');

const dirs = [
  'app/(marketing)/products/[productSlug]',
  'app/(marketing)/pricing',
  'app/(marketing)/about',
  'app/(marketing)/contact',
  'app/(marketing)/cart',
  'app/(marketing)/checkout',
  'app/(marketing)/order-confirmation/[orderId]',
  'app/(auth)/login',
  'app/(auth)/signup',
  'app/(auth)/forgot-password',
  'app/(auth)/verify-email',
  'app/(dashboard)/dashboard',
  'app/(dashboard)/items/[itemId]/settings',
  'app/(dashboard)/items/activate',
  'app/(dashboard)/notifications',
  'app/(dashboard)/tracking',
  'app/(dashboard)/messages',
  'app/(dashboard)/profile',
  'app/(dashboard)/subscription',
  'app/(vendor)/vendor/login',
  'app/(vendor)/vendor/orders/[orderId]',
  'app/scan/[qrCode]',
  'app/activate/[qrCode]',
  'app/api/auth/session',
  'app/api/qr/generate',
  'app/api/qr/scan',
  'app/api/notify/push',
  'app/api/notify/email',
  'app/api/notify/sms',
  'app/api/messages/send',
  'app/api/messages/reply',
  'app/api/orders/create',
  'app/api/orders/update-status',
  'app/api/gps/update',
  'components/ui',
  'components/marketing',
  'components/shop',
  'components/dashboard',
  'components/vendor',
  'components/finder',
  'components/providers',
  'lib/firebase',
  'lib/gsap',
  'lib/three',
  'store',
  'types',
  'hooks',
  'public'
];

dirs.forEach(dir => {
  fs.mkdirSync(path.join(__dirname, dir), { recursive: true });
});

const files = [
  'app/(marketing)/layout.tsx',
  'app/(marketing)/page.tsx',
  'app/(marketing)/products/page.tsx',
  'app/(marketing)/products/[productSlug]/page.tsx',
  'app/(marketing)/pricing/page.tsx',
  'app/(marketing)/about/page.tsx',
  'app/(marketing)/contact/page.tsx',
  'app/(marketing)/cart/page.tsx',
  'app/(marketing)/checkout/page.tsx',
  'app/(marketing)/order-confirmation/[orderId]/page.tsx',
  'app/(auth)/layout.tsx',
  'app/(auth)/login/page.tsx',
  'app/(auth)/signup/page.tsx',
  'app/(auth)/forgot-password/page.tsx',
  'app/(auth)/verify-email/page.tsx',
  'app/(dashboard)/layout.tsx',
  'app/(dashboard)/dashboard/page.tsx',
  'app/(dashboard)/items/page.tsx',
  'app/(dashboard)/items/[itemId]/page.tsx',
  'app/(dashboard)/items/[itemId]/settings/page.tsx',
  'app/(dashboard)/items/activate/page.tsx',
  'app/(dashboard)/notifications/page.tsx',
  'app/(dashboard)/tracking/page.tsx',
  'app/(dashboard)/messages/page.tsx',
  'app/(dashboard)/profile/page.tsx',
  'app/(dashboard)/subscription/page.tsx',
  'app/(vendor)/layout.tsx',
  'app/(vendor)/vendor/login/page.tsx',
  'app/(vendor)/vendor/page.tsx',
  'app/(vendor)/vendor/orders/page.tsx',
  'app/(vendor)/vendor/orders/[orderId]/page.tsx',
  'app/scan/[qrCode]/page.tsx',
  'app/activate/[qrCode]/page.tsx',
  'app/api/auth/session/route.ts',
  'app/api/qr/generate/route.ts',
  'app/api/qr/scan/route.ts',
  'app/api/notify/push/route.ts',
  'app/api/notify/email/route.ts',
  'app/api/notify/sms/route.ts',
  'app/api/messages/send/route.ts',
  'app/api/messages/reply/route.ts',
  'app/api/orders/create/route.ts',
  'app/api/orders/update-status/route.ts',
  'app/api/gps/update/route.ts',
  'app/layout.tsx',
  'app/globals.css',
  'app/not-found.tsx',
  'app/error.tsx',
  'middleware.ts',
  'public/logo.svg',
  'public/favicon.ico',
  'public/og-image.png',
  'public/firebase-messaging-sw.js',
  '.env.local'
];

files.forEach(file => {
  const fullPath = path.join(__dirname, file);
  if (!fs.existsSync(fullPath)) {
    // create empty file
    fs.writeFileSync(fullPath, '');
  }
});
